# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'ahmed_chebbi_ios_challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
  # Pods for ahmed_chebbi_ios_challenge

end
